sound_labels = {
    "Speech": (5, 5),
    "Child speech, kid speaking": (3, 4),
    "Conversation": (5, 5),
    "Narration, monologue": (5, 4),
    "Babbling": (3, 3),
    "Speech synthesizer": (5, 3),
    "Shout": (5, 7),
    "Bellow": (5, 6),
    "Whoop": (5, 6),
    "Yell": (5, 6),
    "Children shouting": (3, 6),
    "Screaming": (5, 7),
    "Whispering": (5, 3),
    "Laughter": (5, 6),
    "Baby laughter": (3, 3),
    "Giggle": (5, 3),
    "Snicker": (5, 3),
    "Belly laugh": (5, 4),
    "Chuckle, chortle": (5, 4),
    "Crying, sobbing": (5, 4),
    "Baby cry, infant cry": (3, 6),
    "Whimper": (5, 3),
    "Wail, moan": (5, 4),
    "Sigh": (5, 3),
    "Singing": (5, 5),
    "Choir": (5, 8),
    "Yodeling": (5, 6),
    "Chant": (5, 5),
    "Mantra": (5, 5),
    "Child singing": (3, 4),
    "Synthetic singing": (5, 5),
    "Rapping": (5, 5),
    "Humming": (5, 5),
    "Groan": (5, 4),
    "Grunt": (5, 4),
    "Whistling": (5, 3),
    "Breathing": (5, 2),
    "Wheeze": (5, 4),
    "Snoring": (5, 4),
    "Gasp": (5, 5),
    "Pant": (5, 5),
    "Snort": (5, 4),
    "Cough": (5, 5),
    "Throat clearing": (5, 4),
    "Sneeze": (5, 3),
    "Sniff": (5, 4),
    "Run": (5, 5),
    "Shuffle": (5, 2),
    "Walk, footsteps": (1, 2),
    "Chewing, mastication": (5, 4),
    "Biting": (5, 4),
    "Gargling": (5, 4),
    "Stomach rumble": (4, 3),
    "Burping, eructation": (5, 4),
    "Hiccup": (5, 4),
    "Fart": (3, 4),
    "Hands": (3, 5),
    "Finger snapping": (5, 4),
    "Clapping": (5, 5),
    "Heart sounds, heartbeat": (4, 2),
    "Heart murmur": (4, 2),
    "Cheering": (5, 7),
    "Applause": (3, 5),
    "Chatter": (5, 5),
    "Crowd": (5, 5),
    "Hubbub, speech noise, speech babble": (5, 5),
    "Children playing": (3, 5),
    "Animal": (3, 5),
    "Domestic animals, pets": (3, 5),
    "Dog": (3, 6),
    "Bark": (3, 8),
    "Yip": (3, 3),
    "Howl": (9, 4),
    "Bow-wow": (3, 3),
    "Growling": (3, 3),
    "Whimper (dog)": (3, 3),
    "Cat": (2, 3),
    "Purr": (2, 2),
    "Meow": (2, 3),
    "Hiss": (2, 3),
    "Caterwaul": (3, 3),
    "Livestock, farm animals, working animals": (4, 5),
    "Horse": (6, 6),
    "Clip-clop": (1, 4),
    "Neigh, whinny": (1, 4),
    "Cattle, bovinae": (5, 5),
    "Moo": (5, 5),
    "Cowbell": (5, 5),
    "Pig": (3, 4),
    "Oink": (3, 4),
    "Goat": (3, 4),
    "Bleat": (3, 4),
    "Sheep": (3, 4),
    "Fowl": (5, 5),
    "Chicken, rooster": (1, 4),
    "Cluck": (1, 4),
    "Crowing, cock-a-doodle-doo": (1, 4),
    "Turkey": (1, 4),
    "Gobble": (1, 4),
    "Duck": (1, 4),
    "Quack": (1, 4),
    "Goose": (1, 4),
    "Honk": (1, 4),
    "Wild animals": (5, 5),
    "Roaring cats (lions, tigers)": (5, 5),
    "Roar": (5, 5),
    "Bird": (8, 1),
    "Bird vocalization, bird call, bird song": (8, 1),
    "Chirp, tweet": (8, 1),
    "Squawk": (8, 1),
    "Pigeon, dove": (8, 1),
    "Coo": (8, 1),
    "Crow": (8, 1),
    "Caw": (8, 1),
    "Owl": (8, 1),
    "Hoot": (8, 1),
    "Bird flight, flapping wings": (8, 2),
    "Canidae, dogs, wolves": (5, 5),
    "Rodents, rats, mice": (5, 5),
    "Mouse": (1, 2),
    "Patter": (1, 2),
    "Insect": (1, 1),
    "Cricket": (5, 1),
    "Mosquito": (6, 1),
    "Fly, housefly": (5, 1),
    "Buzz": (5, 1),
    "Bee, wasp, etc.": (5, 1),
    "Frog": (1, 1),
    "Croak": (1, 1),
    "Snake": (1, 1),
    "Rattle": (5, 1),
    "Whale vocalization": (5, 8),
    "Music": (5, 5),
    "Musical instrument": (5, 5),
    "Plucked string instrument": (5, 5),
    "Guitar": (4, 5),
    "Electric guitar": (4, 5),
    "Bass guitar": (4, 5),
    "Acoustic guitar": (4, 5),
    "Steel guitar, slide guitar": (4, 5),
    "Tapping (guitar technique)": (4, 5),
    "Strum": (4, 5),
    "Banjo": (4, 5),
    "Sitar": (5, 5),
    "Mandolin": (5, 5),
    "Zither": (5, 5),
    "Ukulele": (5, 5),
    "Keyboard (musical)": (4, 5),
    "Piano": (4, 5),
    "Electric piano": (4, 5),
    "Organ": (4, 5),
    "Electronic organ": (5, 5),
    "Hammond organ": (5, 5),
    "Synthesizer": (5, 5),
    "Sampler": (5, 5),
    "Harpsichord": (5, 5),
    "Percussion": (5, 5),
    "Drum kit": (5, 5),
    "Drum machine": (5, 5),
    "Drum": (5, 5),
    "Snare drum": (5, 5),
    "Rimshot": (5, 5),
    "Drum roll": (5, 5),
    "Bass drum": (5, 5),
    "Timpani": (5, 5),
    "Tabla": (5, 5),
    "Cymbal": (5, 5),
    "Hi-hat": (5, 5),
    "Wood block": (5, 5),
    "Tambourine": (5, 5),
    "Rattle (instrument)": (5, 5),
    "Maraca": (5, 5),
    "Gong": (5, 5),
    "Tubular bells": (5, 5),
    "Mallet percussion": (5, 5),
    "Marimba, xylophone": (5, 5),
    "Glockenspiel": (5, 5),
    "Vibraphone": (5, 5),
    "Steelpan": (5, 5),
    "Orchestra": (5, 5),
    "Brass instrument": (5, 5),
    "French horn": (5, 5),
    "Trumpet": (5, 5),
    "Trombone": (5, 5),
    "Bowed string instrument": (5, 5),
    "String section": (5, 5),
    "Violin, fiddle": (5, 5),
    "Pizzicato": (5, 5),
    "Cello": (5, 5),
    "Double bass": (5, 5),
    "Wind instrument, woodwind instrument": (5, 5),
    "Flute": (5, 5),
    "Saxophone": (5, 5),
    "Clarinet": (5, 5),
    "Harp": (5, 5),
    "Bell": (5, 5),
    "Church bell": (5, 5),
    "Jingle bell": (5, 5),
    "Bicycle bell": (5, 5),
    "Tuning fork": (5, 5),
    "Chime": (5, 5),
    "Wind chime": (5, 5),
    "Change ringing (campanology)": (5, 5),
    "Harmonica": (5, 5),
    "Accordion": (5, 5),
    "Bagpipes": (5, 5),
    "Didgeridoo": (5, 5),
    "Shofar": (5, 5),
    "Singing bowl": (5, 5),
    "Scratching (performance technique)": (5, 5),
    "Pop music": (5, 5),
    "Hip hop music": (5, 5),
    "Beatboxing": (5, 5),
    "Rock music": (5, 5),
    "Heavy metal": (5, 5),
    "Punk rock": (5, 5),
    "Grunge": (5, 5),
    "Progressive rock": (5, 5),
    "Rock and roll": (5, 5),
    "Psychedelic rock": (5, 5),
    "Rhythm and blues": (5, 5),
    "Soul music": (5, 5),
    "Reggae": (5, 5),
    "Country": (5, 5),
    "Swing music": (5, 5),
    "Bluegrass": (5, 5),
    "Funk": (5, 5),
    "Folk music": (5, 5),
    "Middle Eastern music": (5, 5),
    "Jazz": (5, 5),
    "Disco": (5, 5),
    "Classical music": (5, 5),
    "Opera": (5, 5),
    "Electronic music": (5, 5),
    "House music": (5, 5),
    "Techno": (5, 5),
    "Dubstep": (5, 5),
    "Drum and bass": (5, 5),
    "Electronica": (5, 5),
    "Electronic dance music": (5, 5),
    "Ambient music": (5, 5),
    "Trance music": (5, 5),
    "Music of Latin America": (5, 5),
    "Salsa music": (5, 5),
    "Flamenco": (5, 5),
    "Blues": (5, 5),
    "Music for children": (5, 5),
    "New-age music": (5, 5),
    "Vocal music": (5, 5),
    "A capella": (5, 5),
    "Music of Africa": (5, 5),
    "Afrobeat": (5, 5),
    "Christian music": (5, 5),
    "Gospel music": (5, 5),
    "Music of Asia": (5, 5),
    "Carnatic music": (5, 5),
    "Music of Bollywood": (5, 5),
    "Ska": (5, 5),
    "Traditional music": (5, 5),
    "Independent music": (5, 5),
    "Song": (5, 5),
    "Background music": (5, 5),
    "Theme music": (5, 5),
    "Jingle (music)": (5, 5),
    "Soundtrack music": (5, 5),
    "Lullaby": (5, 5),
    "Video game music": (5, 5),
    "Christmas music": (5, 5),
    "Dance music": (5, 5),
    "Wedding music": (5, 5),
    "Happy music": (5, 5),
    "Sad music": (5, 5),
    "Tender music": (5, 5),
    "Exciting music": (5, 5),
    "Angry music": (5, 8),
    "Scary music": (5, 5),
    "Wind": (7, 5),
    "Rustling leaves": (5, 5),
    "Wind noise (microphone)": (5, 5),
    "Thunderstorm": (5, 10),
    "Thunder": (5, 10),
    "Water": (3, 5),
    "Rain": (9, 10),
    "Raindrop": (1, 10),
    "Rain on surface": (5, 10),
    "Stream": (2, 5),
    "Waterfall": (8, 5),
    "Ocean": (2, 5),
    "Waves, surf": (2, 5),
    "Steam": (2, 5),
    "Gurgling": (5, 5),
    "Fire": (3, 5),
    "Crackle": (5, 5),
    "Vehicle": (4, 5),
    "Boat, Water vehicle": (2, 5),
    "Sailboat, sailing ship": (2, 5),
    "Rowboat, canoe, kayak": (2, 5),
    "Motorboat, speedboat": (2, 5),
    "Ship": (2, 5),
    "Motor vehicle (road)": (5, 5),
    "Car": (4, 8),
    "Vehicle horn, car horn, honking": (4, 5),
    "Toot": (4, 5),
    "Car alarm": (4, 5),
    "Power windows, electric windows": (4, 5),
    "Skidding": (4, 5),
    "Tire squeal": (4, 5),
    "Car passing by": (4, 5),
    "Race car, auto racing": (4, 5),
    "Truck": (4, 5),
    "Air brake": (4, 5),
    "Air horn, truck horn": (4, 5),
    "Reversing beeps": (4, 5),
    "Ice cream truck, ice cream van": (6, 5),
    "Bus": (6, 5),
    "Emergency vehicle": (6, 5),
    "Police car (siren)": (6, 5),
    "Ambulance (siren)": (6, 5),
    "Fire engine, fire truck (siren)": (6, 5),
    "Motorcycle": (4, 5),
    "Traffic noise, roadway noise": (4, 5),
    "Rail transport": (3, 5),
    "Train": (5, 5),
    "Train whistle": (7, 5),
    "Train horn": (7, 5),
    "Railroad car, train wagon": (5, 5),
    "Train wheels squealing": (5, 5),
    "Subway, metro, underground": (5, 5),
    "Aircraft": (9, 5),
    "Aircraft engine": (9, 5),
    "Jet engine": (9, 5),
    "Propeller, airscrew": (9, 5),
    "Helicopter": (9, 2),
    "Fixed-wing aircraft, airplane": (9, 5),
    "Bicycle": (4, 2),
    "Skateboard": (2, 2),
    "Engine": (5, 5),
    "Light engine (high frequency)": (5, 5),
    "Dental drill, dentist's drill": (5, 3),
    "Lawn mower": (5, 4),
    "Chainsaw": (5, 4),
    "Medium engine (mid frequency)": (5, 5),
    "Heavy engine (low frequency)": (5, 5),
    "Engine knocking": (5, 5),
    "Engine starting": (5, 5),
    "Idling": (5, 5),
    "Accelerating, revving, vroom": (5, 5),
    "Door": (6, 5),
    "Doorbell": (4, 5),
    "Ding-dong": (5, 5),
    "Sliding door": (4, 5),
    "Slam": (4, 5),
    "Knock": (4, 5),
    "Tap": (3, 5),
    "Squeak": (5, 5),
    "Cupboard open or close": (5, 5),
    "Drawer open or close": (4, 5),
    "Dishes, pots, and pans": (3, 5),
    "Cutlery, silverware": (5, 5),
    "Chopping (food)": (5, 4),
    "Frying (food)": (3, 4),
    "Microwave oven": (3, 3),
    "Blender": (4, 4),
    "Water tap, faucet": (5, 3),
    "Sink (filling or washing)": (5, 3),
    "Bathtub (filling or washing)": (5, 3),
    "Hair dryer": (5, 3),
    "Toilet flush": (5, 3),
    "Toothbrush": (5, 3),
    "Electric toothbrush": (5, 3),
    "Vacuum cleaner": (5, 3),
    "Zipper (clothing)": (5, 3),
    "Keys jangling": (5, 3),
    "Coin (dropping)": (5, 3),
    "Scissors": (5, 3),
    "Electric shaver, electric razor": (5, 3),
    "Shuffling cards": (5, 3),
    "Typing": (3, 3),
    "Typewriter": (3, 3),
    "Computer keyboard": (3, 3),
    "Writing": (3, 3),
    "Alarm": (3, 3),
    "Telephone": (3, 5),
    "Telephone bell ringing": (3, 5),
    "Ringtone": (5, 5),
    "Telephone dialing, DTMF": (3, 5),
    "Dial tone": (3, 5),
    "Busy signal": (3, 5),
    "Alarm clock": (3, 5),
    "Siren": (5, 5),
    "Civil defense siren": (5, 5),
    "Buzzer": (5, 5),
    "Smoke detector, smoke alarm": (7, 5),
    "Fire alarm": (7, 5),
    "Foghorn": (5, 5),
    "Whistle": (4, 5),
    "Steam whistle": (4, 5),
    "Mechanisms": (5, 5),
    "Ratchet, pawl": (5, 5),
    "Clock": (3, 3),
    "Tick": (3, 3),
    "Tick-tock": (3, 3),
    "Gears": (5, 5),
    "Pulleys": (5, 5),
    "Sewing machine": (3, 5),
    "Mechanical fan": (7, 5),
    "Air conditioning": (7, 5),
    "Cash register": (3, 5),
    "Printer": (4, 5),
    "Camera": (4, 5),
    "Single-lens reflex camera": (4, 5),
    "Tools": (3, 5),
    "Hammer": (3, 5),
    "Jackhammer": (3, 5),
    "Sawing": (3, 5),
    "Filing (rasp)": (5, 5),
    "Sanding": (5, 5),
    "Power tool": (5, 5),
    "Drill": (5, 5),
    "Explosion": (5, 10),
    "Gunshot, gunfire": (5, 10),
    "Machine gun": (5, 10),
    "Fusillade": (5, 10),
    "Artillery fire": (5, 10),
    "Cap gun": (5, 5),
    "Fireworks": (5, 5),
    "Firecracker": (5, 5),
    "Burst, pop": (5, 5),
    "Eruption": (5, 10),
    "Boom": (5, 10),
    "Wood": (5, 5),
    "Chop": (5, 5),
    "Splinter": (5, 5),
    "Crack": (5, 5),
    "Glass": (4, 5),
    "Shatter": (5, 5),
    "Liquid": (4, 5),
    "Splash, splatter": (5, 5),
    "Slosh": (5, 5),
    "Squish": (5, 5),
    "Drip": (5, 5),
    "Pour": (5, 5),
    "Trickle, dribble": (5, 5),
    "Gush": (5, 5),
    "Fill (with liquid)": (5, 5),
    "Spray": (5, 5),
    "Pump (liquid)": (5, 5),
    "Stir": (5, 5),
    "Boiling": (5, 5),
    "Sonar": (5, 5),
    "Arrow": (5, 5),
    "Whoosh, swoosh, swish": (5, 5),
    "Thump, thud": (5, 5),
    "Thunk": (5, 5),
    "Electronic tuner": (5, 5),
    "Effects unit": (5, 5),
    "Chorus effect": (5, 5),
    "Basketball bounce": (5, 5),
    "Bang": (5, 5),
    "Slap, smack": (5, 5),
    "Whack, thwack": (5, 5),
    "Smash, crash": (5, 5),
    "Breaking": (5, 5),
    "Bouncing": (5, 5),
    "Whip": (5, 5),
    "Flap": (5, 5),
    "Scratch": (5, 5),
    "Scrape": (5, 5),
    "Rub": (5, 5),
    "Roll": (5, 5),
    "Crushing": (5, 5),
    "Crumpling, crinkling": (5, 5),
    "Tearing": (5, 5),
    "Beep, bleep": (5, 5),
    "Ping": (5, 5),
    "Ding": (5, 5),
    "Clang": (5, 5),
    "Squeal": (5, 5),
    "Creak": (5, 5),
    "Rustle": (5, 5),
    "Whir": (5, 5),
    "Clatter": (5, 5),
    "Sizzle": (5, 5),
    "Clicking": (5, 5),
    "Clickety-clack": (5, 5),
    "Rumble": (5, 5),
    "Plop": (5, 5),
    "Jingle, tinkle": (5, 5),
    "Hum": (5, 5),
    "Zing": (5, 5),
    "Boing": (5, 5),
    "Crunch": (5, 5),
    "Silence": (5, 5),
    "Sine wave": (5, 5),
    "Harmonic": (5, 5),
    "Chirp tone": (5, 5),
    "Sound effect": (5, 5),
    "Pulse": (5, 5),
    "Inside, small room": (6, 3),
    "Inside, large room or hall": (8, 3),
    "Inside, public space": (9, 3),
    "Outside, urban or manmade": (9, 5),
    "Outside, rural or natural": (9, 5),
    "Reverberation": (5, 5),
    "Echo": (6, 5),
    "Noise": (4, 5),
    "Environmental noise": (4, 5),
    "Static": (5, 5),
    "Mains hum": (5, 5),
    "Distortion": (5, 5),
    "Sidetone": (5, 5),
    "Cacophony": (5, 5),
    "White noise": (5, 5),
    "Pink noise": (5, 5),
    "Throbbing": (5, 5),
    "Vibration": (5, 5),
    "Television": (4, 5),
    "Radio": (5, 5),
    "Field recording": (5, 5),
}

def get_sound_label(name):
    if name in sound_labels:
        return sound_labels[name][0]
    else:
        return 5
      
def get_sound_intense(name):
    if name in sound_labels:
        return sound_labels[name][1]
    else:
        return 5